tap "anomalyco/tap"
brew "cliclick"
brew "fnm"
brew "git"
brew "herdr"
brew "just"
brew "openai-whisper"
brew "ripgrep"
brew "rtk"
brew "tree"
brew "uv"
brew "vim"
brew "xcodegen"
brew "anomalyco/tap/opencode", trusted: true
cask "google-chrome"
cask "monitorcontrol"
npm "@openai/codex"
npm "firebase-tools"
