tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/services"
brew "readline"
brew "xz"
brew "composer"
brew "go"
brew "dep"
brew "direnv"
brew "ffmpeg"
brew "git"
brew "goenv"
brew "gradle"
brew "hub"
brew "kotlin"
brew "python@2", link: false
brew "mongodb", restart_service: true
brew "mysql@5.7", link: true
brew "nginx"
brew "p7zip"
brew "pyenv"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "rust"
brew "screen"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "zopfli"
brew "zsh"
brew "heroku/brew/heroku"
cask "hyper"
cask "minikube"
cask "virtualbox"
